version: '3.8'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "your_password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - sql_server

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
